name: demo1
on:
    workflow_dispatch

env: 
    GREETING: "welcome"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: create a text file
          run: echo "${{env.GREETING}} ${{secrets.WORLD}}" > ghaction.txt
        - uses: actions/upload-artifact@v4
          with:
            name: ghfile
            path: ghaction.txt

    test:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/download-artifact@v5
              with:
                name: ghfile
            - name: ghaction.txt
              run: ls
            - name: test file
              run: cat ghaction.txt | grep -i "welcome"